<?PHP
 /*
  | Global variables for YAFS (Yet Another Forums System)
  |
  | YAFS copyright: Helicon technologies LTD. 2003
  | YAFS is distributed under the GNU public license
  |
  | This file is part of YAFS (Yet Another Forums System).
  |
  | YAFS is free software; you can redistribute it and/or modify
  | it under the terms of the GNU General Public License as published by
  | the Free Software Foundation;
  |
  | YAFS is distributed in the hope that it will be useful,
  | but WITHOUT ANY WARRANTY; without even the implied warranty of
  | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  | GNU General Public License for more details.
  |
  | You should have received a copy of the GNU General Public License
  | along with the software; if not, write to the Free Software
  | Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
  |
  */
$VerId = 'Version 1.0 Copyright Ori Idan <A HREF=http://www.helicontech.co.il>Helicon technologies</A> Ltd.';

$mainfile="$scriptsurl/index.php";
$editscript="$scriptsurl/editmsg.php";
$loginscript="$scriptsurl/login.php";
$descscript="$scriptsurl/forumdesc.php";
$adminscript="$scriptsurl/forumadmin.php";
$userlist="$scriptsurl/userlist.php";
$nulfrm="$scriptsurl/nulfrm.php";
$privatemsg="$scriptsurl/msg.php";
$addfilescript="$scriptsurl/addpic.php";
$banscript="$scriptsurl/ban.php";
$chainscript="$scriptsurl/chain.php";
/* $artcleslistscript="$scriptsurl/articles.php";
$miniforumscript="$scriptsurl/showarticle.php"; */

?>
