escforums.tar.gz: editmsg.php forumadmin.php forumdesc.php login.php config.inc readme.txt escforum.php
#	rm escforums.tar.gz
	tar -cvf escforums.tar readme.txt COPYING config.inc escforum.php login.php forumdesc.php editmsg.php forumadmin.php emoticons/*.*
	gzip escforums.tar
